/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const boot_app: (a: number) => void;
export const connect_avatar_ws: (a: number, b: number, c: number) => void;
export const get_avatar_ws_status: (a: number) => void;
export const get_blendshape_json: (a: number) => void;
export const get_last_assistant_message: (a: number) => void;
export const init_kimi: (a: number, b: number) => void;
export const is_streaming: () => number;
export const read_pixels: () => number;
export const send_message: (a: number, b: number) => void;
export const set_blendshape_frame: (a: number, b: number, c: number) => void;
export const set_theme: (a: number, b: number) => void;
export const inject_test_messages: () => void;
export const render_frame: () => void;
export const get_streaming_length: () => number;
export const resize: (a: number, b: number) => void;
export const scroll: (a: number) => void;
export const __wasm_bindgen_func_elem_4672: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_4665: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_3034: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_497: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_497_3: (a: number, b: number, c: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_export5: (a: number, b: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
